# PyTorch container
# PyTorch: https://pytorch.org/
# NVIDIA Container: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/
#FROM nvcr.io/nvidia/pytorch:25.04-py3
#RUN apt update -y && apt install -y libgl1-mesa-dev xvfb
FROM nvcr.io/nvidia/pytorch:25.04-py3
RUN apt update -y && apt install -y libgl1-mesa-dev xvfb